--- #YAML:1.0
name:               Algorithm-SpatialIndex
version:            0.04
abstract:           Flexible 2D/3D spacial indexing
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::XSAccessor:  1.05
    lib:                0
    Module::Pluggable:  0
    parent:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
